#pragma once

#include "p2d/Body.hpp"

namespace p2d {

// Rigid joints -- genuinely bilateral (equality) velocity constraints
// solved by World's sequential-impulse solver, the same technique contacts
// use, NOT a force (contrast SpringJoint, which is Hooke's-law-plus-damping
// and genuinely springy/stretchy under load). These hold firmly: a
// DistanceJoint's length, or a RevoluteJoint's shared pivot, doesn't sag
// under weight the way a very stiff spring still would.
//
// All four store their anchor(s) in body-LOCAL space (localAnchorA is in
// `a`'s local frame, localAnchorB in `b`'s) so they track correctly as
// each body rotates -- World::createDistanceJoint() and friends take a
// world-space anchor point and convert it once, at creation time.
//
// Each has a warm-starting accumulator (named `impulse`/`pointImpulse`/
// etc.), carried over step to step exactly like Contact::normalImpulse --
// unlike a Contact, a joint is never regenerated by broadphase (it's
// always active between its fixed two bodies), so the accumulator just
// lives directly on the joint object instead of needing a prevContacts_-
// style lookup map.

// Keeps two anchor points exactly `length` apart. 1 constrained DOF
// (distance); relative rotation and sliding are otherwise free -- think of
// it as a rigid rod or a taut, inextensible rope between the two anchors.
struct DistanceJoint {
    Body* a = nullptr;
    Body* b = nullptr;
    Vec2 localAnchorA;
    Vec2 localAnchorB;
    float length = 0.0f;

    float impulse = 0.0f;
};

// Pins one anchor point on A to one on B (both coincide in world space).
// 2 constrained DOF (position); relative rotation is completely free --
// a door hinge, a wheel on an axle, a pendulum's pivot.
struct RevoluteJoint {
    Body* a = nullptr;
    Body* b = nullptr;
    Vec2 localAnchorA;
    Vec2 localAnchorB;

    Vec2 impulse;
};

// RevoluteJoint's point constraint PLUS a fixed relative angle -- 3
// constrained DOF total (position + rotation), a full rigid connection as
// if the two bodies were welded together at the anchor (while still being
// two separate bodies/masses, each with their own mass properties). Solved
// as two independent constraints in sequence (point, then angle) rather
// than one coupled 3x3 system -- a deliberate simplification (see
// World::solveVelocities()) that still converges to a correctly rigid weld
// at rest, just not via the exact same transient path a fully-coupled
// solve would take.
struct WeldJoint {
    Body* a = nullptr;
    Body* b = nullptr;
    Vec2 localAnchorA;
    Vec2 localAnchorB;
    float referenceAngle = 0.0f; // b->rotation - a->rotation, captured at creation

    Vec2 pointImpulse;
    float angleImpulse = 0.0f;
};

// Constrains B to slide along a fixed axis (given in A's local space)
// relative to A, with no relative rotation allowed -- 2 constrained DOF
// (perpendicular-to-axis position + rotation), 1 free DOF (sliding
// distance along the axis). A piston, a drawer, a platform that only moves
// straight up and down. Solved as two independent constraints (same
// simplification as WeldJoint, for the same reason).
struct PrismaticJoint {
    Body* a = nullptr;
    Body* b = nullptr;
    Vec2 localAnchorA;
    Vec2 localAnchorB;
    Vec2 localAxisA{1.0f, 0.0f}; // slide direction, in A's local space
    float referenceAngle = 0.0f;

    float perpImpulse = 0.0f;
    float angleImpulse = 0.0f;
};

} // namespace p2d
